# Generated by Django 4.1.3 on 2023-01-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_employee_iteams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteams',
            name='image',
            field=models.ImageField(max_length=40, upload_to='', verbose_name='Image'),
        ),
    ]
