# Generated by Django 4.1.3 on 2023-01-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_iteams_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteams',
            name='iteam_mes_para',
            field=models.CharField(choices=[('Numbers', 'Numbers'), ('Meter', 'Meter'), ('KG', 'KG'), ('Kilo Meter', 'Kilo Meter')], max_length=40, verbose_name='Messure'),
        ),
    ]
