# Generated by Django 4.1.3 on 2023-01-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_iteams_iteam_mes_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteams',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='iteams',
            name='iteam_code',
            field=models.IntegerField(verbose_name='Iteam Code'),
        ),
        migrations.AlterField(
            model_name='iteams',
            name='iteam_mes_para',
            field=models.CharField(choices=[('Numbers', 'Numbers'), ('Meter', 'Meter'), ('KG', 'KG'), ('Kilo Meter', 'Kilo Meter')], default='Numbers', max_length=40, verbose_name='Messure'),
        ),
        migrations.AlterField(
            model_name='iteams',
            name='iteam_qty',
            field=models.IntegerField(verbose_name='Iteam Qty'),
        ),
    ]
